name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Milai Bot Service Deployment
        run: |
            cd milai
            flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.MILAI_SERVICE }}
